# @host = http://localhost:5000/vpo/v1
@host = https://virtualparishoffice.herokuapp.com/vpo/v1
###
POST {{host}}/persons/create
Content-Type: application/json

{
	"firstname":"Estefanía",
	"secondname":"Karina",
	"lastname":"Marcos",
	"secondlastname":"Gutierrez",
	"dpi":"3393791032101",
	"sexo":"F",
	"address":"Caserio Araizapo Aldea el Durazno Jalapa"
}

###
GET {{host}}/persons/many/G
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTU0ZDY1MGEtZWY4YS00YjExLTkwYTEtY2MxNGI5MzBkYTJmIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjAzMjY3NTkwLCJpc3MiOiJtYXJvbGQ5N0BvdXRsb29rLmNvbSJ9.TC39U-bJYk1hEnNDSVHmLPKzJTHiSDlm2Sr0bSHkFB6Xk3Nxpwk7joFUMcUmkCiAqauFzycjHsLcvx63Nb2bOP7ta2kwEQHk3EahbnX2_suEKioNoFZzcgbBbh9s2-XaFLEYKx0NphL4LxsQ43Prx3BOYFfcBkhofetPqwll1W8

###
GET {{host}}/persons/priest
Content-Type: application/json

###
POST {{host}}/persons/priest
Content-Type: application/json

{
	"firstname_priest":"",
	"secondname_priest":"",
	"lastname_priest":"",
	"second_lastname_priest":"",
	"credentials":""
}

###
GET {{host}}/persons/priests/count
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTU0ZDY1MGEtZWY4YS00YjExLTkwYTEtY2MxNGI5MzBkYTJmIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjAyODM4Nzk4LCJpc3MiOiJtYXJvbGQ5N0BvdXRsb29rLmNvbSJ9.KwVKbhYYO5CwgHisdXGoaZkajOtJowDlt4HMBZ9WaCt74xFCOZkWAptvkxRyzQcpbAuiGYvqS9YiAnHcpPrrdELmYDPkpmfc6RuqWFbB46zuKE89XHFgLiIjhCSGCMsrNej1mXskIKEnAxNwD1fEydN_fy6Tgmds63bWZYEg9MY

###
GET {{host}}/persons/priest/Ca
Content-Type: application/json

###
GET {{host}}/persons/baptized
Content-Type: application/json

###
GET {{host}}/persons/partida/89ed8a75-08e8-45fb-9a35-9f95e7f447c8
Content-Type: application/json


###
DELETE http://localhost:5000/vpo/v1/persons/partida/1


###
GET {{host}}/persons/by/50/Guti
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTU0ZDY1MGEtZWY4YS00YjExLTkwYTEtY2MxNGI5MzBkYTJmIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjAzNjU2MTMzLCJpc3MiOiJtYXJvbGQ5N0BvdXRsb29rLmNvbSJ9.ll_Z7ZkWGFyC1vylgHXrP0ClfWoBmN0Tg9xZ7H7cyyN0qtrLUZhzSHk6PbeHuomhL9WTdElURIv1bfAWPnh1O5KuKUtl9hlpfpRktMMTwvgywkv-92YnOeYUd_uwLw1HinMcavjmPqiEUBuXuNpXJg7uvLVPx5hr9T6ZXeipUAE

###
PUT {{host}}/persons/108dccf6-b425-4909-8bf6-cfd1c30bcee9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTU0ZDY1MGEtZWY4YS00YjExLTkwYTEtY2MxNGI5MzBkYTJmIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjAzNjU2MTMzLCJpc3MiOiJtYXJvbGQ5N0BvdXRsb29rLmNvbSJ9.ll_Z7ZkWGFyC1vylgHXrP0ClfWoBmN0Tg9xZ7H7cyyN0qtrLUZhzSHk6PbeHuomhL9WTdElURIv1bfAWPnh1O5KuKUtl9hlpfpRktMMTwvgywkv-92YnOeYUd_uwLw1HinMcavjmPqiEUBuXuNpXJg7uvLVPx5hr9T6ZXeipUAE

{
	"firstname":"Estefanía",
	"secondname":"Marina",
	"lastname":"Marcos",
	"secondlastname":"Gutierrez",
	"sexo":"F"
}